// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: auth2soc.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MakeNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name  string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image string `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *MakeNodeRequest) Reset() {
	*x = MakeNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth2soc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeNodeRequest) ProtoMessage() {}

func (x *MakeNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth2soc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeNodeRequest.ProtoReflect.Descriptor instead.
func (*MakeNodeRequest) Descriptor() ([]byte, []int) {
	return file_auth2soc_proto_rawDescGZIP(), []int{0}
}

func (x *MakeNodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MakeNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MakeNodeRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type MakeNodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *MakeNodeResponse) Reset() {
	*x = MakeNodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_auth2soc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeNodeResponse) ProtoMessage() {}

func (x *MakeNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth2soc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeNodeResponse.ProtoReflect.Descriptor instead.
func (*MakeNodeResponse) Descriptor() ([]byte, []int) {
	return file_auth2soc_proto_rawDescGZIP(), []int{1}
}

func (x *MakeNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MakeNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_auth2soc_proto protoreflect.FileDescriptor

var file_auth2soc_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x32, 0x73, 0x6f, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x61, 0x75, 0x74, 0x68, 0x32, 0x73, 0x6f, 0x63, 0x22, 0x4b, 0x0a, 0x0f, 0x4d, 0x61,
	0x6b, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x46, 0x0a, 0x10, 0x4d, 0x61, 0x6b, 0x65, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32,
	0x58, 0x0a, 0x0f, 0x41, 0x75, 0x74, 0x68, 0x32, 0x53, 0x6f, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x19, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x32, 0x73, 0x6f, 0x63, 0x2e, 0x4d, 0x61, 0x6b, 0x65,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x32, 0x73, 0x6f, 0x63, 0x2e, 0x4d, 0x61, 0x6b, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_auth2soc_proto_rawDescOnce sync.Once
	file_auth2soc_proto_rawDescData = file_auth2soc_proto_rawDesc
)

func file_auth2soc_proto_rawDescGZIP() []byte {
	file_auth2soc_proto_rawDescOnce.Do(func() {
		file_auth2soc_proto_rawDescData = protoimpl.X.CompressGZIP(file_auth2soc_proto_rawDescData)
	})
	return file_auth2soc_proto_rawDescData
}

var file_auth2soc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_auth2soc_proto_goTypes = []any{
	(*MakeNodeRequest)(nil),  // 0: auth2soc.MakeNodeRequest
	(*MakeNodeResponse)(nil), // 1: auth2soc.MakeNodeResponse
}
var file_auth2soc_proto_depIdxs = []int32{
	0, // 0: auth2soc.Auth2SocService.CreateNode:input_type -> auth2soc.MakeNodeRequest
	1, // 1: auth2soc.Auth2SocService.CreateNode:output_type -> auth2soc.MakeNodeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth2soc_proto_init() }
func file_auth2soc_proto_init() {
	if File_auth2soc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_auth2soc_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MakeNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_auth2soc_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MakeNodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_auth2soc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth2soc_proto_goTypes,
		DependencyIndexes: file_auth2soc_proto_depIdxs,
		MessageInfos:      file_auth2soc_proto_msgTypes,
	}.Build()
	File_auth2soc_proto = out.File
	file_auth2soc_proto_rawDesc = nil
	file_auth2soc_proto_goTypes = nil
	file_auth2soc_proto_depIdxs = nil
}
