services:
  mail_service:
    build: .
    container_name: "mail_service"
    env_file:
      - ".env"
    depends_on:
      - "rabbitmq"
  rabbitmq:
    image: "rabbitmq:latest"
    ports:
      - "5672:5672"
      - "15672:15672"
  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "1025:1025"
      - "8025:8025"
